databases:
  - name: dailydrivedb 
    databaseName: dailydrivedb 
    user: dailydrivedb 

services:
  - type: web
    name: dailydrive 
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn dailydrive.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dailydrive 
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4